create table AUX_FILE (id bigint not null auto_increment, created_date date not null, description varchar(255), filename varchar(255) not null, uri varchar(255) not null, patient_id varchar(255), primary key (id))
create table BASELINE_DIAGNOSIS (id bigint not null auto_increment, age float, dbp varchar(255), diagnosis_date date not null, heart_rate varchar(255), height varchar(255), history_of_alcohol varchar(255), history_of_diabetes varchar(255), history_of_hypertension varchar(255), history_of_smoking varchar(255), sbp varchar(255), weight varchar(255), patient_id varchar(255), primary key (id))
create table CAP_MODEL (id bigint not null auto_increment, comment varchar(255), created_date date not null, model_data longblob, name varchar(255) not null, type varchar(255), xml_data longblob, patient_id varchar(255), primary key (id))
create table CLINICAL_NOTE (id bigint not null auto_increment, age float, assessment_date date not null, diagnosis varchar(255), height varchar(255), notes varchar(255) not null, weight varchar(255), patient_id varchar(255), primary key (id))
create table PATIENT_HISTORY (id bigint not null auto_increment, created_time date, event_date date not null, modified_time date, pacs_patient_id varchar(255), primary key (id))
create table PATIENT_INFO (patient_id varchar(255) not null, cohort varchar(255) not null, ethnicity varchar(255), gender varchar(255) not null, primary_diagnosis varchar(255), primary key (patient_id))
create table USER (id bigint not null auto_increment, enabled bit, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (id))
alter table AUX_FILE add constraint FK_AUX_FILE_PATIENT_INFO_Id foreign key (patient_id) references PATIENT_INFO (patient_id)
alter table BASELINE_DIAGNOSIS add constraint FK_BASELINE_DIAGNOSIS_PATIENT_INFO_Id foreign key (patient_id) references PATIENT_INFO (patient_id)
alter table CAP_MODEL add constraint FK_CAP_MODEL_PATIENT_INFO_Id foreign key (patient_id) references PATIENT_INFO (patient_id)
alter table CLINICAL_NOTE add constraint FK_CLINICAL_NOTE_PATIENT_INFO_Id foreign key (patient_id) references PATIENT_INFO (patient_id)
alter table PATIENT_HISTORY add constraint FK_PATIENT_HISTORY_PATIENT_INFO_Id foreign key (pacs_patient_id) references PATIENT_INFO (patient_id)
