-- MySQL Script generated by MySQL Workbench
-- Wed Aug 17 16:59:29 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xpacs
-- -----------------------------------------------------
-- Xtra PACS database
DROP SCHEMA IF EXISTS `xpacs` ;

-- -----------------------------------------------------
-- Schema xpacs
--
-- Xtra PACS database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xpacs` DEFAULT CHARACTER SET utf8 ;
USE `xpacs` ;

-- -----------------------------------------------------
-- Table `xpacs`.`STUDY_PACS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`STUDY_PACS` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `PACS_StudyInstanceUID` VARCHAR(250) NOT NULL,
  `PACS_PatientID` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpacs`.`CAP_MODEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`CAP_MODEL` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Type` VARCHAR(255) NULL,
  `Comment` VARCHAR(2500) NULL,
  `ModelData` LONGBLOB NULL COMMENT 'Model definition stored as a zip file (BLOB)',
  `XMLData` LONGBLOB NULL COMMENT 'Contains XML metadata information.',
  `STUDY_PACS_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `STUDY_PACS_id`),
  INDEX `fk_CAP_MODEL_STUDY_PACS1_idx` (`STUDY_PACS_id` ASC),
  CONSTRAINT `fk_CAP_MODEL_STUDY_PACS1`
    FOREIGN KEY (`STUDY_PACS_id`)
    REFERENCES `xpacs`.`STUDY_PACS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpacs`.`AUX_FILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`AUX_FILE` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `URI` VARCHAR(255) NULL,
  `Filename` VARCHAR(255) NULL,
  `Descriptor` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpacs`.`CLINICAL_NOTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`CLINICAL_NOTE` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Age` VARCHAR(64) NULL,
  `Weight` VARCHAR(64) NULL,
  `Height` VARCHAR(64) NULL,
  `Diagnosis` VARCHAR(255) NULL,
  `Procedure` VARCHAR(255) NULL,
  `Notes` VARCHAR(2500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpacs`.`PATIENT_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`PATIENT_HISTORY` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `EventDate` DATETIME NOT NULL,
  `Next_id` BIGINT(20) NULL,
  `Prev_id` BIGINT(20) NULL,
  `STUDY_PACS_id` BIGINT(20) NULL,
  `CLINICAL_NOTE_id` BIGINT(20) NULL,
  `AUX_FILE_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PATIENT_HISTORY_PATIENT_HISTORY1_idx` (`Next_id` ASC),
  INDEX `fk_PATIENT_HISTORY_PATIENT_HISTORY2_idx` (`Prev_id` ASC),
  INDEX `fk_PATIENT_HISTORY_STUDY_PACS1_idx` (`STUDY_PACS_id` ASC),
  INDEX `fk_PATIENT_HISTORY_CLINICAL_NOTE1_idx` (`CLINICAL_NOTE_id` ASC),
  INDEX `fk_PATIENT_HISTORY_AUX_FILE1_idx` (`AUX_FILE_id` ASC),
  CONSTRAINT `fk_PATIENT_HISTORY_PATIENT_HISTORY1`
    FOREIGN KEY (`Next_id`)
    REFERENCES `xpacs`.`PATIENT_HISTORY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATIENT_HISTORY_PATIENT_HISTORY2`
    FOREIGN KEY (`Prev_id`)
    REFERENCES `xpacs`.`PATIENT_HISTORY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATIENT_HISTORY_STUDY_PACS1`
    FOREIGN KEY (`STUDY_PACS_id`)
    REFERENCES `xpacs`.`STUDY_PACS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATIENT_HISTORY_CLINICAL_NOTE1`
    FOREIGN KEY (`CLINICAL_NOTE_id`)
    REFERENCES `xpacs`.`CLINICAL_NOTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATIENT_HISTORY_AUX_FILE1`
    FOREIGN KEY (`AUX_FILE_id`)
    REFERENCES `xpacs`.`AUX_FILE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpacs`.`PATIENT_INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`PATIENT_INFO` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `PatientID` VARCHAR(8) NULL COMMENT 'This should be unique patient ID which are the first 8 digits of the STUDY_PACS.PACS_patient_id',
  `Cohort` VARCHAR(256) NULL,
  `Gender` VARCHAR(2) NULL,
  `first_history_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`, `first_history_id`),
  UNIQUE INDEX `patient_id_UNIQUE` (`PatientID` ASC),
  INDEX `fk_PATIENT_INFO_PATIENT_HISTORY1_idx` (`first_history_id` ASC),
  CONSTRAINT `fk_PATIENT_INFO_PATIENT_HISTORY1`
    FOREIGN KEY (`first_history_id`)
    REFERENCES `xpacs`.`PATIENT_HISTORY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpacs`.`BASELINE_DIAGNOSIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`BASELINE_DIAGNOSIS` (
  `id` BIGINT(20) NOT NULL,
  `STUDY_PACS_id` BIGINT(20) NOT NULL,
  `Ethnicity` VARCHAR(64) NULL,
  `Height` VARCHAR(64) NULL,
  `Weight` VARCHAR(64) NULL,
  `SBP` VARCHAR(64) NULL,
  `DBP` VARCHAR(64) NULL,
  `HeartRate` VARCHAR(64) NULL,
  `HistoryOfHypertension` VARCHAR(16) NULL,
  `HistoryOfDiabetes` VARCHAR(16) NULL,
  `HistoryOfAlcohol` VARCHAR(16) NULL,
  `HistoryOfSmoking` VARCHAR(16) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CLINICAL_MESA_STUDY_PACS1_idx` (`STUDY_PACS_id` ASC),
  CONSTRAINT `fk_CLINICAL_MESA_STUDY_PACS1`
    FOREIGN KEY (`STUDY_PACS_id`)
    REFERENCES `xpacs`.`STUDY_PACS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
